language: node_js
node_js:
  - "12"
  - "11"
  - "10"
  - "9"
cache: yarn
stages:
  - build
  - test
  - release
env:
  global:
    - COVERALLS_PARALLEL=true
before_install:
  # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
  - openssl aes-256-cbc -K $encrypted_0fe340a46a4e_key -iv $encrypted_0fe340a46a4e_iv -in git_deploy_key.enc -out /tmp/git_deploy_key -d
  # Make sure only the current user can read the private key
  - chmod 600 /tmp/git_deploy_key
  # Create a script to return the passphrase environment variable to ssh-add
  - echo 'echo ${SSH_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
  # Start the authentication agent
  - eval "$(ssh-agent -s)"
  # Add the key to the authentication agent
  - DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
jobs:
  include:
    - stage: build
    - script: yarn build
    
    - stage: test
    - script: yarn test
    - script: yarn coverage
    
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: yarn semantic-release
